export { default as Dashboard } from './dashboard/Dashboard.jsx';
export { default as Home } from './home/Home.jsx';
export { default as Auth } from './auth/Auth.jsx';
export { default as Profile } from './user/Profile.jsx';
export { default as AccountActivation } from './user/AccountActivation.jsx';
export { default as Logout } from './auth/Logout.jsx';
export { default as PosCreate } from './pos/create/PosCreate.jsx';
export { default as DisplayPos } from './pos/display/DisplayPos.jsx';
export { default as UpdatePos } from './pos/update/UpdatePos.jsx';