export { default as Dashboard } from './dashboard/Dashboard.jsx';
export { default as Home } from './home/Home.jsx';
export { default as Auth } from './auth/Auth.jsx';
// export { default as Roles } from './auth/Roles.js';
// export { default as Guard } from './auth/Guard.jsx';
export { default as Profile } from './user/Profile.jsx';
export { default as AccountActivation } from './user/AccountActivation.jsx';
export { default as Logout } from './auth/Logout.jsx';
export { default as PosCreate } from './pos/create/PosCreate.jsx';
export { default as DisplayPos } from './pos/display/DisplayPos.jsx';
export { default as UpdatePos } from './pos/update/UpdatePos.jsx';
export { default as CreateBranch } from './pos/create/CreateBranch.jsx';
export { default as DisplayBranch } from './pos/display/DisplayBranch.jsx';
export { default as CreateSupplier } from './supplier/create/CreateSupplier.jsx';
export { default as DisplaySupplier } from './supplier/display/DisplaySupplier.jsx';
export { default as CreateProduct } from './products/create/CreateProduct.jsx';
export { default as CreateProductCategory } from './products/create/CreateProductCategory.jsx';
export { default as ProductList } from './products/display/ProductList.jsx';
export { default as ProductsDisplay } from './products/display/ProductsDisplay.jsx';
export { default as BestDeals } from './products/display/BestDeals.jsx';
export { default as ProductEvents } from './products/display/ProductEvents.jsx';
export { default as DisplayCategory } from './products/display/DisplayCategory.jsx';
export { default as FeaturedProducts } from './products/display/FeaturedProducts.jsx';
export { default as Orders } from './order/Orders.jsx';